import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const generateMetadata = async ({ params }: any) => {
  const titleFromAPI = "Judul apaan nih ?";
  return {
    title: titleFromAPI,
    description: "Ini deskripsi",
  };
};

export const metadata = {
  title: "Next guidline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
